package com.example.util

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.widget.Toast
import com.example.model.Daemon
import com.example.model.Task
import com.example.model.TaskState
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

object MarkdownExportHelper {

    fun generateMarkdown(
        tasks: List<Task>,
        archive: List<Task>,
        daemons: Map<String, Daemon>
    ): String {
        val now = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
        val sb = StringBuilder()

        sb.append("# ❄️ ColdCache.OS // System Journal\n")
        sb.append("> **Export Date:** `$now`  \n")
        sb.append("> **Status:** Optimal Flow  \n\n")

        // Daemons Section
        sb.append("## ⚡ Active Daemons Status\n")
        if (daemons.isEmpty()) {
            sb.append("_No active daemons configured._\n\n")
        } else {
            daemons.values.forEach { d ->
                val pct = if (d.max > 0) ((d.current.toFloat() / d.max) * 100).toInt().coerceIn(0, 100) else 0
                val check = if (d.current >= d.max) "✅" else "⏳"
                sb.append("- **${d.label.uppercase()}** ($check `$pct%`): `${d.current}/${d.max}` (Type: `${d.type.name}`)\n")
            }
            sb.append("\n")
        }

        // Active RAM Section
        val ramTasks = tasks.filter { it.state == TaskState.ACTIVE_RAM }
        sb.append("## 🧠 Active RAM Slots (${ramTasks.size}/3)\n")
        if (ramTasks.isEmpty()) {
            sb.append("_RAM is clean. Ready for high-focus task allocation._\n\n")
        } else {
            ramTasks.forEach { t ->
                sb.append("### ⚡ ${t.title} (Weight: ${t.weight}%, Progress: ${t.progress}%)\n")
                if (t.scheduledDate != null) {
                    sb.append("> 📅 **Scheduled:** `${t.scheduledDate} ${t.scheduledTime ?: ""}`\n")
                }
                if (t.subtasks.isNotEmpty()) {
                    sb.append("#### Subtasks:\n")
                    t.subtasks.forEach { st ->
                        val mark = if (st.done) "[x]" else "[ ]"
                        sb.append("- $mark ${st.text}\n")
                    }
                }
                sb.append("\n")
            }
        }

        // Latent Space / Buffer Section
        val bufferTasks = tasks.filter { it.state == TaskState.BUFFER }
        sb.append("## 📥 Buffer // Fast Memory Stream (${bufferTasks.size})\n")
        if (bufferTasks.isEmpty()) {
            sb.append("_Buffer empty._\n\n")
        } else {
            bufferTasks.forEach { t ->
                sb.append("- [ ] ${t.title}\n")
            }
            sb.append("\n")
        }

        // Cryo Section
        val cryoTasks = tasks.filter { it.state == TaskState.CRYO }
        sb.append("## 🧊 Cryo Storage // Deferred Tasks (${cryoTasks.size})\n")
        if (cryoTasks.isEmpty()) {
            sb.append("_Cryo chamber empty._\n\n")
        } else {
            cryoTasks.forEach { t ->
                val sched = if (t.scheduledDate != null) " (📅 ${t.scheduledDate})" else ""
                sb.append("- [ ] ${t.title}$sched\n")
            }
            sb.append("\n")
        }

        // Completed Archive / Render Log Section
        sb.append("## 📜 Completed Render Log (${archive.size})\n")
        if (archive.isEmpty()) {
            sb.append("_No completed tasks recorded in archive yet._\n\n")
        } else {
            val groupedByDate = archive.groupBy { it.completedAt?.take(10) ?: "Undated" }
            groupedByDate.forEach { (date, items) ->
                sb.append("### 📅 $date (${items.size} resolved)\n")
                items.forEach { item ->
                    val time = item.completedAt?.drop(11)?.take(5) ?: ""
                    val timeStr = if (time.isNotBlank()) "`$time` " else ""
                    sb.append("- [x] $timeStr${item.title}\n")
                }
                sb.append("\n")
            }
        }

        sb.append("---\n*Generated by ColdCache.OS // Deep Focus Engine*")
        return sb.toString()
    }

    fun exportAndShare(
        context: Context,
        tasks: List<Task>,
        archive: List<Task>,
        daemons: Map<String, Daemon>
    ) {
        val markdown = generateMarkdown(tasks, archive, daemons)

        // 1. Copy to clipboard
        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
        val clip = ClipData.newPlainText("ColdCache Markdown Journal", markdown)
        clipboard.setPrimaryClip(clip)

        // 2. Open Android Share Sheet
        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/markdown"
            putExtra(Intent.EXTRA_SUBJECT, "ColdCache.OS Journal Export")
            putExtra(Intent.EXTRA_TEXT, markdown)
            flags = Intent.FLAG_ACTIVITY_NEW_TASK
        }
        val chooser = Intent.createChooser(shareIntent, "Экспорт журнала ColdCache в Markdown")
        chooser.flags = Intent.FLAG_ACTIVITY_NEW_TASK
        context.startActivity(chooser)

        Toast.makeText(context, "✓ [ MARKDOWN ] Скопировано в буфер и готово к отправке", Toast.LENGTH_SHORT).show()
    }
}
